<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class formHandler extends Model
{
   use HasFactory;

   protected $fillable = [
      "student-name-bangla",
      "student-name-english",
      "birth-certificate-number",
      "birth-date",
      "student-mobile",
      "blood-group",
      "gender",
      "marital-status",
      "father-name-bangla",
      "father-name-english",
      "mother-name-bangla",
      "mother-name-english",
      "father-nid",
      "mother-nid",
      "father-birth-date",
      "mother-birth-date",
      "father-mobile",
      "mother-mobile",
      "pres_division",
      "pres_district",
      "pres_upozilla",
      "pres-city-corp",
      "pres-post-code",
      "pres-address",
      "perm_division",
      "perm_district",
      "perm_upozilla",
      "perm-city-corp",
      "perm-post-code",
      "perm-address",
      "pe_division",
      "pe_district",
      "pe_upozilla",
      "pe-board",
      "pe-institute",
      "pe-passing-year",
      "pe-gpa",
      "pe-exam-name",
      "pe-technology-trade",
      "pe-roll",
      "pe-att-rate",
      "ce_division",
      "ce_district",
      "ce_upozilla",
      "ce-institute-name",
      "ce-semester",
      "ce-technology-trade",
      "ce-shift",
      "ce-group",
      "ce-roll",
      "ce-reg",
      "relationship",
      "guardian-name-bangla",
      "guardian-name-english",
      "guardian-nid",
      "guardian-birth-date",
      "guardian-mobile",
      "cost-borne",
      "ethnic",
      "ffq",
      "scholarship",
      "disabilities",
      "payment-method",
      "mobile-bank-provider",
      "mobile-bank-account",
      "bank-name",
      "bank-branch",
      "bank-routing",
      "bank-acc-type",
      "bank-acc-name",
      "bank-acc-number",
      "formal_image_path",
      "signature_image_path",
   ];

   protected $table = "form_handlers";
}
